### PR TITLE
introduce ember-cli-addon-docs

### PR DESCRIPTION
**Pull request by hakubo**
Recently I've found
https://ember-learn.github.io/ember-cli-addon-docs/master/

and I just couldn't resist to try it somewhere. It looks good I have to say.

What do you think? Worth it?
to see how it looks just run 
`ember s` and go to localhost:4200/docs

### CODE REVIEW

**Comment by mydea** [comment]
Generally, that looks really nice! I pushed some additional changes, improving the styling/docs slightly.

There are still a few things I'm unclear about:

**Comment by hakubo** [comment]
1. search does seem to work for me - it's not perfect but it works
2. https://ember-learn.github.io/ember-cli-addon-docs/latest/docs/deploying
after a release you run ember deploy production and it should work
we could setup automatic deploying of master docs as well

**Comment by mydea** [comment]
LGTM, I'll merge it and try to use ember-cli-deploy!

**Comment by mydea** [comment]
FYI, I have now set up everything, looks good! Thanks for the work!
Although, the search is still not working for me here: https://cropster.github.io/ember-visual-test - but that's not that big of a deal right now, I guess.

**Pull request merged**
